name: CI/CD for Frappe Custom Application

# Trigger this action on pull requests to the dev branch
on:
  push:
    branches:
      - test

jobs:
  

  bench-restart:
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
      
        - name: Run bench migrate
          uses: appleboy/ssh-action@master
          with:
           host: ${{ secrets.HOST }}
           port: 2222
           username: fervent
           key: ${{ secrets.SSH_PRIVATE_KEY }} # Your SSH private key secret
           script: |
             cd /home/fervent/fervent/apps/fusion_hr
              name: CI/CD for Frappe Custom Application

# Trigger this action on pull requests to the dev branch
on:
  pull_request:
    branches:
      - dev

jobs:
  deploy-pull:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v2

    # Set up SSH access
    - name: pull from dev branch on server
      uses: appleboy/ssh-action@master
      with:
         host: ${{ secrets.HOST }}
         port: 2222
         username: fervent
         key: ${{ secrets.SSH_PRIVATE_KEY }} # Your SSH private key secret
         script: |
           cd /home/fervent/fervent/apps/fusion_hr
           git pull upstream dev

  bench-migrate:
      runs-on: ubuntu-latest
      needs: deploy-pull

      steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run bench migrate
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.HOST }}
         port: 2222
         username: fervent
         key: ${{ secrets.SSH_PRIVATE_KEY }} # Your SSH private key secret
         script: |
           cd /home/fervent/fervent/apps/fusion_hr
           bench migrate

  bench-restart:
        runs-on: ubuntu-latest
        needs: bench-migrate
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
      
        - name: Run bench migrate
          uses: appleboy/ssh-action@master
          with:
           host: ${{ secrets.HOST }}
           port: 2222
           username: fervent
           key: ${{ secrets.SSH_PRIVATE_KEY }} # Your SSH private key secret
           script: |
             cd /home/fervent/fervent/apps/fusion_hr
             sudo -S <<< ${{ secrets.SUDO_PASSWORD }} bench restart

       
         
   


       
         
   
