name: CI/CD for Frappe Custom Application

# Trigger this action on pull requests to the dev branch
on:
  push:
    branches:
      - test

jobs:
  

  bench-restart:
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
      
        - name: Run bench migrate
          uses: appleboy/ssh-action@master
          with:
           host: ${{ secrets.HOST }}
           port: 2222
           username: fervent
           key: ${{ secrets.SSH_PRIVATE_KEY }} # Your SSH private key secret
           script: |
             cd /home/fervent/fervent/apps/fusion_hr
              echo ${{ secrets.SUDO_PASSWORD}} | sudo -S bench restart

       
         
   
